### ISSUE TITLE
Add Meteor.Device.isTouch()

### ISSUE THREAD

**Issue by gb96** [mystor/meteor-device-detection#10]
For my project, I don't care if the Device is Desktop/Laptop/TV/Phone/Tablet/Bot etc, what I really want to know is if there is a Touch interface or not. Generally you can assume Phone/Tablet have touch, but others are more difficult to tell. You could have a Desktop with Touch in which case I would like to provide the same touch UI features as I do on Phone/Tablet.

Is it possible to define isTouch based on device detection?

**Comment by mystor** [comment]
This library was written using a set of user agent regexes which attempt to identify whether a user is on mobile or desktop. I would recommend not using this library if the type of responsiveness you want in your app is touch/not-touch, as it can't actually tell. If you want to perform feature detection, as it seems you do, I recommend using Modernizr or similar (http://modernizr.com/).
