### ISSUE TITLE
How does this work with Cordova?

### ISSUE THREAD

**Issue by t3db0t** [mystor/meteor-device-detection#12]
If the application is Cordova, what value will detectDevice() return?

**Comment by mystor** [comment]
I have no idea. I haven't done any work with meteor/cordova, and the detectDevice methods work by checking user agent. My guess is it would probably default to mobile.

**Comment by t3db0t** [comment]
Gotcha—I will probably try it out soon and report back ;)

**Comment by t3db0t** [comment]
Indeed, tried it out on the iOS simulator and it gave me the "phone" template.
